Content discovery blog post
n0-computer/iroh.computer pull request #144
Opened 2024-06-27 15:12 UTC by rklaehn

First draft of a blog post about content discovery

2024-06-28 08:29 UTC, matheus23 commented on src/app/blog/iroh-content-discovery/page.mdx
> +bittorrent mainline DHT. It's most fundamental function is to associate a SHA1
```suggestion
bittorrent mainline DHT. Its most fundamental function is to associate a SHA1
```

2024-06-28 08:34 UTC, matheus23 commented on src/app/blog/iroh-content-discovery/page.mdx
> +has the content gets online.
```suggestion
has the content goes online.
```

2024-06-28 08:35 UTC, matheus23 commented on src/app/blog/iroh-content-discovery/page.mdx
> +This step is entirely optional. If you have an use case where the tracker to use
```suggestion
This step is entirely optional. If you have a use case where the tracker to use
```

2024-07-01 09:51 UTC, dignifiedquire commented on src/app/blog/iroh-content-discovery/page.mdx
> +  title: 'Iroh content discovery',
I think the title is a bit vague, maybe sth like "content discovery explorations" or in that direction

2024-07-01 09:58 UTC, dignifiedquire commented on src/app/blog/iroh-content-discovery/page.mdx
> +# Current state
- should also have a future/what we are planning to do section, so folks understand where this is going

2024-07-01 18:30 UTC, ramfox requested changes
another great blog post!

This has the same formatting that concerns me with the DAG blog post as well, where a `\n` character has been added after every X number of characters in the line, which could cause weird formatting in smaller displays like a phone.

2024-07-01 18:30 UTC, ramfox commented on src/app/blog/iroh-content-discovery/page.mdx
> +The just acts as a last resort to find a tracker in case either you don't know
```suggestion
The DHT just acts as a last resort to find a tracker in case either you don't know
```

2024-07-01 18:30 UTC, ramfox commented on src/app/blog/iroh-content-discovery/page.mdx
> +after getting them, and then discarding all announces that have not ever been
```suggestion
after getting them, and then discarding all announces that have not been
```

2024-07-01 18:30 UTC, ramfox commented on src/app/blog/iroh-content-discovery/page.mdx
> +storing the announce. This would be a further way to reduce the work to be done
```suggestion
storing the announce. This would be a way to further reduce the work to be done
```

2024-07-01 18:30 UTC, ramfox commented on src/app/blog/iroh-content-discovery/page.mdx
> +to force the tracker to do futile connection attempts to non-existing node ids.
```suggestion
force the tracker to do futile connection attempts to non-existing node ids.
```

2024-07-01 18:30 UTC, ramfox commented on src/app/blog/iroh-content-discovery/page.mdx
> +- iroh-mainline-content-discovery defines the protocol for announcing and querying
```suggestion
- `iroh-mainline-content-discovery` defines the protocol for announcing and querying
```

2024-07-01 18:30 UTC, ramfox commented on src/app/blog/iroh-content-discovery/page.mdx
> +- iroh-mainline-content-discovery-cli is a cli tool that uses the client to announce
```suggestion
- `iroh-mainline-content-discovery-cli` is a cli tool that uses the client to announce
```

2024-07-01 18:30 UTC, ramfox commented on src/app/blog/iroh-content-discovery/page.mdx
> +- iroh-mainline-tracker is a tracker using [redb](https://github.com/cberner/redb) as
```suggestion
- `iroh-mainline-tracker` is a tracker using [redb](https://github.com/cberner/redb) as
```

2024-07-02 15:05 UTC, rklaehn commented on src/app/blog/iroh-content-discovery/page.mdx
> +# Problem
Current state?

2024-07-11 19:16 UTC, merged